version: "3.8"

services:
  coolify:
    image: coollabsio/coolify
    container_name: coolify
    ports:
      - "3000:3000"
    volumes:
      - coolify-data:/app/data
    environment:
      - NODE_ENV=production
    restart: always

volumes:
  coolify-data:
